name: 🚀 Cypress Tests with Allure

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: Run Cypress and generate Allure Report

    steps:
      - name: 🧱 Checkout Code
        uses: actions/checkout@v3

      - name: 🟢 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install Dependencies
        run: npm ci

      - name: 🧪 Run Cypress tests
        run: npx cypress run --env allure=true

      - name: ☕ Install Java for Allure
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 📊 Generate Allure Report
        run: |
          npm install -g allure-commandline --save-dev
          allure generate allure-results --clean -o allure-report

      - name: 📤 Upload Allure Report Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: allure-report
          path: allure-report
